#!/usr/bin/env python3
"""Generate the static site. Edit content/services.json and posts.json; run python3 scripts/build_site.py."""
from pathlib import Path
from html import escape, unescape
import json, re, datetime

ROOT = Path(__file__).resolve().parent.parent
SITE = 'https://www.simpleconsulting.ca'
TODAY = '2026-09-15'
SERVICES = json.loads((ROOT/'content/services.json').read_text())
BY_KEY = {s['key']:s for s in SERVICES}
GENERAL = {'key':'general','slug':'services','label':'E-commerce consulting services','fit':'Explore practical support for your channels, operations, website and advertising. We can discuss which service fits your situation.'}
POSTS = json.loads((ROOT/'posts.json').read_text())
CORE = ['index.html','services.html','about.html','booking.html','privacy.html','blog.html']+[s['slug']+'.html' for s in SERVICES]
E = lambda s: escape(str(s), quote=True)
def plain(s): return unescape(re.sub('<[^>]+>',' ',s)).strip()
def url(file): return SITE + ('/' if file=='index.html' else '/'+file)
def slugify(s):
    return re.sub(r'[^a-z0-9]+','-',s.lower().replace("'","").replace('’','')).strip('-')[:70]
def postdate(p): return datetime.datetime.strptime(p['date'],'%b %d, %Y').strftime('%Y-%m-%d')
def service_for(p):
    if p.get('service'): return BY_KEY.get(p['service'], GENERAL)
    t=p['title'].lower()
    if 'walmart' in t: k='walmart'
    elif 'amazon' in t: k='amazon'
    elif 'google ads' in t or p['tag']=='Google Ads': k='google'
    elif p['tag']=='ERP' or any(x in t for x in ['dashboard','power bi','data to make','edi']): k='systems'
    elif p['tag']=='Operations' or any(x in t for x in ['3pl','fulfillment','forecast','supply','supplier','inventory','chargeback']): k='operations'
    elif p['tag']=='E-commerce' or 'shopify' in t or 'e-commerce website' in t: k='shopify'
    elif any(x in t for x in ['monthly business review','e-commerce employee','wholesale','strategic partnership']): k='fractional'
    else: return GENERAL
    return BY_KEY[k]
def nav(file):
    items=[('services.html','Services'),('amazon-management.html','Amazon'),('walmart-management.html','Walmart'),('about.html','About'),('blog.html','Insights')]
    def links():
        return ''.join(f'<a href="/{f}"'+(' aria-current="page"' if f==file else '')+f'>{label}</a>' for f,label in items)
    cta='<a class="btn" data-event="review_click" href="/booking.html#booking">Book a free call</a>'
    return f'''<a class="skip" href="#main">Skip to content</a><header class="site-header"><nav class="container site-nav" aria-label="Main navigation"><a class="logo" href="/">Simple Consulting<span>.</span></a><div class="desktop-links">{links()}{cta}</div><details class="mobile-menu"><summary>Menu</summary><div class="mobile-links">{links()}<a href="/reimbursement-recovery.html">Reimbursement reviews</a><a href="/ecommerce-operations.html">Inventory &amp; fulfilment</a><a href="/booking.html#start">Send a message</a>{cta}</div></details></nav></header>'''
def footer():
    links=''.join(f'<a href="/{s["slug"]}.html">{E(s["label"])}</a>' for s in SERVICES)
    return f'''<footer class="site-footer"><div class="container"><div class="footer-top"><div><a class="logo" href="/">Simple Consulting<span>.</span></a><p>E-commerce and marketplace operations.<br>Toronto, Ontario · Serving Canada and the US.</p><a href="mailto:scott@simpleconsulting.ca" data-event="email_click">scott@simpleconsulting.ca</a></div><div><h2>Services</h2><div class="footer-links">{links}</div></div><div><h2>Start a conversation</h2><div class="footer-links"><a href="/booking.html#booking">Book a free 30-minute call</a><a href="/booking.html#start">Send a message</a><a href="/booking.html#assessment">Assess your Amazon or Walmart channel</a><a href="/about.html">About Scott</a><a href="/blog.html">Insights</a><a href="https://www.linkedin.com/in/scott-nguyen-0b97723a0" rel="me">LinkedIn</a><a href="https://www.instagram.com/simpleconsulting.ca/" rel="me">Instagram</a><a href="/privacy.html">Privacy &amp; enquiries</a></div></div></div><div class="footer-bottom">© 2026 Simple Consulting. Independent consulting. Retailer and platform names describe services and experience; they do not imply affiliation, endorsement or partnership.</div></div></footer>'''
def btns(key='',assessment=False):
    q='?service='+key if key else ''
    return f'''<div class="actions"><a class="btn" data-event="review_click" href="/booking.html{q}#booking">Book a free call</a><a class="btn secondary" data-event="message_click" href="/booking.html{q}#start">Send a message</a></div><p class="hero-note">30 minutes · Work directly with Scott · No preparation needed</p>'''
def cta(key=''):
    q='?service='+key if key else ''
    return f'''<section class="bottom-cta"><div class="container"><div><h2>What keeps landing back on your desk?</h2><p>Tell me about the channel or recurring issue. We will talk through where help would make a difference and a practical next step.</p></div><a class="btn" data-event="review_click" href="/booking.html{q}#booking">Book a free call</a></div></section>'''
def faq(items):
    return '<div class="faq">'+''.join(f'<details><summary>{E(q)}</summary><p>{E(a)}</p></details>' for q,a in items)+'</div>'
def service_card(s,n=None):
    number=f'<span class="card-number">{n:02d}</span>' if n else ''
    return f'''<div class="card">{number}<h3>{E(s['label'])}</h3><p>{E(s['fit'])}</p><a class="card-link" href="/{s['slug']}.html">Explore {E(s['label'].lower())} →</a></div>'''
def base(file,title,description,body,extra_schema=None,scripts='',robots=None):
    canonical=url(file)
    org={'@type':'Organization','@id':SITE+'/#organization','name':'Simple Consulting','url':SITE+'/','email':'scott@simpleconsulting.ca','founder':{'@id':SITE+'/about.html#scott'},'areaServed':[{'@type':'Country','name':'Canada'},{'@type':'Country','name':'United States'}],'location':{'@type':'Place','name':'Toronto, Ontario, Canada'},'sameAs':['https://www.linkedin.com/in/scott-nguyen-0b97723a0','https://www.instagram.com/simpleconsulting.ca/']}
    person={'@type':'Person','@id':SITE+'/about.html#scott','name':'Scott Nguyen','url':SITE+'/about.html','jobTitle':'E-commerce and marketplace consultant','worksFor':{'@id':SITE+'/#organization'}}
    page={'@type':'WebPage','@id':canonical+'#page','url':canonical,'name':title,'description':description,'inLanguage':'en-CA','isPartOf':{'@id':SITE+'/#website'},'about':{'@id':SITE+'/#organization'}}
    graph=[org,person,{'@type':'WebSite','@id':SITE+'/#website','url':SITE+'/','name':'Simple Consulting','publisher':{'@id':SITE+'/#organization'}},page]+(extra_schema or [])
    schema=json.dumps({'@context':'https://schema.org','@graph':graph},ensure_ascii=False).replace('</','<\\/')
    is_post=file.startswith('blog/')
    text=f'''<!doctype html><html lang="en-CA"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{E(title)}</title><meta name="description" content="{E(description)}"><link rel="canonical" href="{canonical}"><meta name="theme-color" content="#1a4d3a"><meta name="author" content="Scott Nguyen"><meta property="og:type" content="{'article' if is_post else 'website'}"><meta property="og:title" content="{E(title)}"><meta property="og:description" content="{E(description)}"><meta property="og:url" content="{canonical}"><meta property="og:site_name" content="Simple Consulting"><meta property="og:locale" content="en_CA"><meta name="twitter:card" content="summary"><link rel="icon" type="image/svg+xml" href="/assessment/favicon.svg"><link rel="stylesheet" href="/assets/site.css"><script type="application/ld+json">{schema}</script>{'<meta name="robots" content="'+robots+'">' if robots else ''}<script src="/assets/site.js" defer></script>{scripts}</head><body>{nav(file)}<main id="main">{body}</main>{footer()}</body></html>'''
    target=ROOT/file;target.parent.mkdir(parents=True,exist_ok=True);target.write_text(text)
def home():
    choices=[('amazon','Amazon tasks keep piling up'),('walmart','Walmart needs more attention'),('operations','Stock and fulfilment feel reactive')]
    body=f'''<section class="hero"><div class="container hero-grid"><div><p class="eyebrow">Marketplace management for Canadian brands</p><h1>Amazon &amp; Walmart.<br><span class="hero-emphasis">Managed.</span></h1><p class="lead">Your accounts need attention. Your business needs you. I take on the listings, advertising, inventory and day-to-day follow-through that keep your marketplace channels moving.</p><p class="hero-audience">For brands, manufacturers and distributors selling in Canada and the US.</p>{btns()}</div><aside class="start-card" aria-label="Meet Scott and find your starting point"><div class="hero-person"><img src="/1765937561010.png" width="64" height="80" alt="Scott Nguyen, founder of Simple Consulting"><div><strong>Scott Nguyen</strong><span>Your point of contact.<br>The person doing the work.</span></div></div><h2>What needs attention?</h2>{''.join(f'<a class="service-choice" href="/{BY_KEY[k]["slug"]}.html">{E(label)}<span aria-hidden="true">↗</span></a>' for k,label in choices)}<p class="small muted">One issue or ongoing account management.<br><a href="/booking.html#start">Tell me what is happening →</a></p></aside></div></section>
    <div class="trust-strip"><div class="container trust-row"><div><strong>15+ years</strong><span>Across retail and e-commerce</span></div><div><strong>9 years at Staples Canada</strong><span>Part of my retail background</span></div><div><strong>Work directly with Scott</strong><span>From first call to follow-through</span></div><div><strong>Toronto, Ontario</strong><span>Serving Canada and the US</span></div></div></div>
    <section class="section" id="services"><div class="container"><div class="section-heading"><p class="eyebrow">Three places to start</p><h2>Get the work off your desk.<br>Keep the business in your hands.</h2><p class="lead">Bring in support for one channel or the operating problems connecting them.</p></div><div class="grid">{''.join(service_card(BY_KEY[k],i+1) for i,k in enumerate(['amazon','walmart','operations']))}</div></div></section>
    <section class="section soft"><div class="container"><div class="section-heading"><p class="eyebrow">What the support looks like</p><h2>Someone keeping track.<br>Someone following through.</h2><p class="lead">When a listing issue, late shipment or reporting question keeps coming back to you, the work needs a clear owner.</p></div><div class="grid work-grid"><div><span class="step-number">01</span><h3>The right issues first</h3><p>We identify what is blocking sales or creating repeat work, check the relevant records and put the priorities in order.</p></div><div><span class="step-number">02</span><h3>The details connected</h3><p>I consider listings, advertising and stock together, then coordinate the account tasks, shipments and follow-ups I take on.</p></div><div><span class="step-number">03</span><h3>A clear view of the work</h3><p>You can see what has been done, what is outstanding and where a decision is needed. We review the measures that matter to your business.</p></div></div></div></section>
    <section class="section" id="about-scott"><div class="container split"><img class="founder-image" src="/1765937561010.png" width="340" height="425" alt="Scott Nguyen, founder of Simple Consulting" loading="lazy"><div><p class="eyebrow">Meet the person you will work with</p><h2>Hi, I'm Scott.</h2><p class="lead">My background spans more than 15 years in retail, e-commerce and operations, including nine years at Staples Canada.</p><p>My work sits where the account meets the operation: product information, campaigns, purchase orders, stock, fulfilment, returns and reporting. I help connect those moving parts and take responsibility for the work we agree I will own.</p><p>You speak with me from the first conversation and work with me through delivery.</p><a href="/about.html">More about my experience →</a></div></div></section>
    <section class="section soft"><div class="container"><div class="section-heading"><p class="eyebrow">A practical way to start</p><h2>One problem today.<br>The right support as you grow.</h2></div><div class="grid"><div class="card"><h3>A focused project</h3><p>Get help with a specific listing, campaign, inventory issue or reconciliation. A useful starting point when you know what needs attention.</p><a class="card-link" href="/booking.html#start">Tell me about the issue →</a></div><div class="card"><h3>Ongoing management</h3><p>Put recurring marketplace work in experienced hands, with agreed responsibilities and regular visibility into progress.</p><a class="card-link" href="/services.html">Explore account support →</a></div><div class="card"><h3>A broader operating role</h3><p>Bring together priorities across your channels, internal team and providers when you need an experienced e-commerce lead.</p><a class="card-link" href="/fractional-ecommerce-manager.html">Explore fractional support →</a></div></div><div class="supporting-note"><h3>Need help beyond the marketplace account?</h3><p>Related support includes <a href="/reimbursement-recovery.html">reimbursement reviews</a>, <a href="/shopify-consulting.html">Shopify &amp; DTC</a>, <a href="/ecommerce-systems-reporting.html">systems &amp; Power BI reporting</a> and <a href="/google-ads-management.html">Google Ads &amp; Shopping</a>.</p></div></div></section>
    <section class="section"><div class="container"><h2>A few questions before we talk.</h2>{faq([('Can you help with just one issue?','Yes. We can start with a focused project, such as a listing problem, campaign review, inventory plan or records reconciliation. You do not need to begin with ongoing management.'),('Can you work with my existing team or agency?','Yes. I can own a defined part of the work and coordinate with the people already involved. We make the responsibilities clear at the start.'),('What happens on the first call?','We spend 30 minutes discussing your channels, the issue and what you have already tried. I will explain where I may be able to help and what I would look at next. The call is free; any detailed review or implementation is priced separately.'),('What if I am not ready to book?','Send a short message instead. Tell me what is happening and include your store or website link if useful. I reply within one business day.')])}</div></section>{cta()}'''
    base('index.html','Amazon & Walmart Account Management Canada | Simple Consulting','Hands-on Amazon and Walmart account management for Canadian brands. Listings, advertising, inventory and fulfilment with Scott Nguyen. Book a free call.',body)
def service_pages():
    for s in SERVICES:
        body=f'''<div class="container crumbs"><a href="/">Home</a> / <a href="/services.html">Services</a> / {E(s['label'])}</div><section class="page-hero"><div class="container"><p class="eyebrow">{E(s['label'])}</p><h1>{E(s['heading'])}</h1><p class="lead">{E(s['intro'])}</p>{btns(s['key'])}</div></section><section class="section"><div class="container service-layout"><div class="service-content">'''
        for i,sec in enumerate(s['sections']):
            title,p,*lists=sec
            body+=f'<section id="section-{i+1}"><h2>{E(title)}</h2><p>{E(p)}</p>'
            if lists: body+='<ul>'+''.join('<li>'+E(x)+'</li>' for x in lists[0])+'</ul>'
            body+='</section>'
        body+=f'''</div><aside class="service-sidebar"><h2>A good fit</h2><p>{E(s['fit'])}</p><hr><h2>What you can expect</h2><p>{E(s['deliverable'])}</p><hr><h2>Talk it through with Scott</h2><p>The first 30-minute call is free. We will talk through the issue and agree on the work and fees before starting.</p><a class="btn" href="/booking.html?service={s['key']}#booking">Book a free call</a><a href="/booking.html?service={s['key']}#start">Prefer to send a message?</a></aside></div></section><section class="section soft"><div class="container"><h2>Questions before we start</h2>{faq(s['faq'])}</div></section><section class="section"><div class="container"><h2>Related support</h2><div class="grid">{''.join(service_card(BY_KEY[k]) for k in s['related'])}</div></div></section>{cta(s['key'])}'''
        canonical=url(s['slug']+'.html')
        schemas=[{'@type':'Service','@id':canonical+'#service','name':s['label'],'serviceType':s['heading'].rstrip('.'),'description':s['intro'],'url':canonical,'provider':{'@id':SITE+'/#organization'},'areaServed':[{'@type':'Country','name':'Canada'},{'@type':'Country','name':'United States'}]},{'@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Home','item':SITE+'/'},{'@type':'ListItem','position':2,'name':'Services','item':SITE+'/services.html'},{'@type':'ListItem','position':3,'name':s['label'],'item':canonical}]}]
        base(s['slug']+'.html',s['title'],s['description'],body,schemas)
def services_hub():
    body=f'''<section class="page-hero"><div class="container"><p class="eyebrow">Marketplace &amp; e-commerce services</p><h1>The channel work.<br>The operations behind it.</h1><p class="lead">Start with Amazon, Walmart or a recurring inventory and fulfilment problem. I can take on a focused project, manage the ongoing work or coordinate priorities across your channels.</p>{btns()}</div></section><section class="section"><div class="container"><div class="section-heading"><p class="eyebrow">Core services</p><h2>Where I can take work off your plate.</h2></div><div class="grid">{''.join(service_card(BY_KEY[k],i+1) for i,k in enumerate(['amazon','walmart','operations']))}</div></div></section><section class="section soft"><div class="container"><div class="section-heading"><p class="eyebrow">Supporting your wider business</p><h2>Connect the work around your channels.</h2><p>Choose these services when the issue extends into your store, records, reporting, advertising or the coordination between teams.</p></div><div class="grid two">{''.join(service_card(BY_KEY[k]) for k in ['reimbursement','fractional','shopify','systems','google'])}</div></div></section><section class="section"><div class="container split"><div><p class="eyebrow">Other retail channels</p><h2>Working with another retailer?</h2></div><div><p class="lead">My background also includes Best Buy Canada, Costco, Wayfair, Home Depot and other retail channels.</p><p>Tell me which retailer you work with and where you need help: product setup, onboarding, fulfilment or the recurring account work.</p><a href="/booking.html#start">Tell me about your channel →</a></div></div></section>{cta()}'''
    base('services.html','Marketplace & E-commerce Consulting Canada | Simple Consulting','Amazon and Walmart management, inventory and fulfilment consulting, with supporting Shopify, reporting and fractional e-commerce services. Work with Scott.',body)
def about():
    body=f'''<section class="page-hero"><div class="container"><p class="eyebrow">About Scott Nguyen</p><h1>An experienced operator.<br>Your day-to-day partner.</h1><p class="lead">I'm the founder of Simple Consulting, based in Toronto. I help brands, manufacturers and distributors manage marketplace accounts and the inventory, fulfilment and reporting behind them.</p>{btns()}</div></section><section class="section"><div class="container split"><img class="founder-image" src="/1765937561010.png" width="340" height="425" alt="Scott Nguyen, founder of Simple Consulting"><div><h2>A practical perspective, built over 15+ years.</h2><p>My background spans retail, e-commerce and operations, including nine years in progressive roles at Staples Canada. My experience across Amazon, Walmart and other channels has developed through that broader career.</p><p>I work on the details that connect channel performance: listings, advertising, stock availability, purchase orders, fulfilment, returns and reporting. A useful recommendation needs an owner and a way to put it into practice.</p><p>You work with me directly. We agree on responsibilities, access, approvals and the reporting cadence before work begins.</p><a href="https://www.linkedin.com/in/scott-nguyen-0b97723a0">View my professional background on LinkedIn →</a></div></div></section><section class="section soft"><div class="container"><h2>Where I can help</h2><div class="grid"><div class="card"><h3>Marketplaces and retail</h3><p>Amazon Vendor Central, Seller Central and FBA; Walmart Marketplace and WFS; and experience with Best Buy, Costco, Wayfair, Home Depot and other retail channels.</p></div><div class="card"><h3>Operations and process</h3><p>Inventory planning, fulfilment coordination, returns, vendor requirements and practical process improvement informed by Lean Six Sigma training.</p></div><div class="card"><h3>Systems and reporting</h3><p>ERP, Power BI, business-system integration, Google Ads and analytics work that connects the available information to operating decisions.</p></div></div><p class="small muted" style="margin-top:24px"></p></div></section><section class="section"><div class="container"><div class="section-heading"><p class="eyebrow">Working together</p><h2>Clear priorities. Direct communication. Agreed responsibilities.</h2><p class="lead">A project can address one defined issue. Ongoing management can cover recurring channel tasks. Fractional support can coordinate priorities across your wider business.</p><p>Start by telling me what is happening and what you want to improve. We will discuss the right scope and the information needed to assess it.</p></div><a href="/services.html">Explore the services →</a></div></section>{cta()}'''
    base('about.html','Scott Nguyen | E-commerce & Marketplace Consultant Canada','Meet Scott Nguyen, founder of Simple Consulting in Toronto. More than 15 years across retail, e-commerce and operations. Direct, practical channel support.',body)
def booking():
    options=''.join(f'<option value="{s["key"]}">{E(s["label"])}</option>' for s in SERVICES)
    body=f'''<section class="page-hero"><div class="container"><p class="eyebrow" id="contact-eyebrow">Start a conversation</p><h1 id="contact-heading">Let’s get the work moving.</h1><p class="lead" id="contact-intro">Book a free 30-minute call or send a short message. We can discuss Amazon, Walmart, Shopify or the operations around your channels.</p><div class="actions"><a class="btn" href="#booking">Book a free call</a><a class="btn secondary" href="#start">Send a message</a></div><p class="hero-note">A short description is enough to start. No presentation or account access needed.</p></div></section>
    <section class="section"><div class="container contact-layout"><section id="start"><h2>What's on your mind?</h2><p class="muted">A sentence or two is enough to start. I'll reply within one business day.</p><form class="contact-form" id="leadform" action="https://formspree.io/f/mreegwjn" method="post"><input type="hidden" name="_subject" value="Simple Consulting website enquiry"><input type="hidden" name="source_page" id="source-page" value="booking.html"><div class="hp" aria-hidden="true"><label for="company_website">Leave this blank</label><input type="text" id="company_website" name="_gotcha" autocomplete="off" tabindex="-1"></div><div class="form-row"><div class="field"><label for="name">Your name</label><input id="name" name="name" autocomplete="name" required maxlength="150"><p class="error" id="name-error" hidden>Add your name.</p></div><div class="field"><label for="email">Email</label><input type="email" id="email" name="email" autocomplete="email" required maxlength="254"><p class="error" id="email-error" hidden>Enter a valid email address so I can reply.</p></div></div><div class="field"><label for="channel">What would you like help with? <span class="muted">(optional)</span></label><select id="channel" name="channel"><option value="">Choose a service, or leave this open</option>{options}<option value="both">Amazon and Walmart</option><option value="other">Another retailer or not sure yet</option></select></div><div class="field"><label for="message">Your message</label><textarea id="message" name="message" required minlength="5" maxlength="12000" placeholder="Which channel or part of the business needs attention? Include your website or store link if useful."></textarea><p class="error" id="message-error" hidden>Add a short message about what you need.</p></div><button class="btn form-submit" type="submit" id="send-button">Send message</button><p class="status" id="send-status" role="status" aria-live="polite"></p><p class="small muted">Your message goes to Scott. Sending an enquiry does not subscribe you to marketing emails. <a href="/privacy.html">About your enquiry</a>.</p></form><div id="form-success" class="callout" hidden tabindex="-1"><h2>Your enquiry was submitted.</h2><p>Thank you. I'll reply within one business day. You can also email <a href="mailto:scott@simpleconsulting.ca">scott@simpleconsulting.ca</a>.</p></div><button class="btn secondary" type="button" id="copy-enquiry">Copy your enquiry</button><p class="status" id="copy-status" role="status"></p><textarea class="copy-fallback" id="copy-fallback" aria-label="Enquiry to copy" hidden></textarea></section>
    <aside class="contact-aside" id="booking"><div class="contact-person"><img src="/1765937561010.png" width="70" height="85" alt="Scott Nguyen" loading="lazy"><p><strong>Speak directly with Scott</strong><br><span class="small muted">Toronto, Ontario · Canada</span></p></div><h2>Book a free call.</h2><p>Choose a time for a free 30-minute call. Tell me what is happening, ask your questions and we will work out a useful next step.</p><a class="btn" id="calendar-direct" data-event="booking_open" href="https://calendly.com/scottnguyen416/30min" target="_blank" rel="noopener noreferrer">Choose a time ↗<span class="small"> &nbsp;(new tab)</span></a><p class="small muted" style="margin-top:15px">Choose a time in your timezone. If you have already written a message, use “Copy your enquiry” to add it to your booking notes.</p><button type="button" class="btn secondary" id="load-calendar">Show the calendar here</button><div id="calendar-slot" class="calendar-slot" hidden></div><p class="small muted" id="calendar-status" role="status"></p><hr style="border:0;border-top:1px solid var(--line);margin:26px 0"><h3>What to bring</h3><p>A description of your business, your channels and what you want to improve. No password, account access or prepared presentation is needed.</p><p class="small">Prefer email? <a href="mailto:scott@simpleconsulting.ca" data-event="email_click">scott@simpleconsulting.ca</a></p></aside></div>
    <div class="container" id="assessment"><details class="assessment-panel" id="assessment-panel"><summary>Not sure what your Amazon or Walmart channel needs? Try the optional 2-minute assessment.</summary><p>Choose your channels and issues to create a starting summary. No contact details are required. Nothing is sent until you choose to share it.</p><iframe id="assessment-frame" title="Optional Amazon and Walmart channel assessment" data-src="/assessment/index.html?embed=1" hidden></iframe><noscript><p><a href="/assessment/index.html">Open the assessment</a>. You can book or send a message without completing it.</p></noscript></details></div></section>
    <section class="section soft"><div class="container"><h2>Before you get in touch</h2>{faq([('What does the first review include?','A free 30-minute conversation to understand your situation, identify what to examine next and discuss a suitable scope. A detailed account audit or implementation is separate work unless agreed otherwise.'),('Do I need to know exactly which service I need?','No. Describe the problem and we can work out whether the starting point is the account, advertising, inventory, store, reporting or a broader operating role.'),('Can we start with a focused project?','Yes. A specific issue may suit a project before you consider ongoing support.'),('When will I hear back?','I reply to messages within one business day. If you book a call, Calendly confirms your selected time and meeting details.')])}</div></section>'''
    base('booking.html','Free E-commerce & Marketplace Review | Simple Consulting','Book a free 30-minute call or message Scott about Amazon, Walmart, Shopify, inventory, advertising or e-commerce operations. Based in Toronto, Canada.',body,scripts='<script src="/assets/contact.js" defer></script>')
def privacy():
    body='''<section class="page-hero"><div class="container"><p class="eyebrow">Privacy & enquiries</p><h1>About the information you share here.</h1><p class="lead">Use the contact form, email or booking link to start a conversation with Scott at Simple Consulting.</p></div></section><section class="section"><div class="container article-shell"><h2>Enquiry information</h2><p>The contact form asks for your name, email and message. You can optionally choose a service. It also includes the page or service source to help explain your enquiry. Formspree processes the form and delivers it to Scott. The information is used to respond to your request and discuss the work you are considering.</p><p>Sending an enquiry does not subscribe you to marketing emails. Please do not include passwords, payment-card information or sensitive customer records in this form. We can agree on a suitable way to share relevant project records if needed.</p><h2>Booking a call</h2><p>The booking link opens Calendly. You can also choose to load its calendar on this page. Information you provide there is processed by Calendly for booking. Details typed into the message form are not automatically forwarded to the calendar.</p><h2>The optional assessment</h2><p>The assessment creates a summary from the answers you select. Its answers remain in your browser tab until you choose to share them. Adding the summary to the message form does not send it; review the message and press Send when ready.</p><h2>Third-party services</h2><p>Formspree, Calendly, the website host and your email provider may process information as part of delivering their services. Their policies explain their handling of that information. This website does not automatically load an advertising or analytics tracker in the current version.</p><p><a href="https://formspree.io/legal/privacy-policy/">Formspree privacy policy</a> · <a href="https://calendly.com/privacy">Calendly privacy policy</a> · <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub privacy statement</a></p><h2>Questions about your information</h2><p>Email <a href="mailto:scott@simpleconsulting.ca">scott@simpleconsulting.ca</a> to ask about your enquiry or request correction or deletion. Scott will respond to discuss the request and any relevant record-keeping requirements.</p></div></section>'''
    base('privacy.html','Privacy & Enquiries | Simple Consulting','How enquiries, booking details and optional channel-assessment answers are handled on the Simple Consulting website.',body)
def blog():
    seen=set()
    for p in POSTS:
        slug=p.get('slug') or slugify(p['title'])
        if slug in seen: raise ValueError('Duplicate post slug: '+slug)
        seen.add(slug);p['slug']=slug
    sorted_posts=sorted(POSTS,key=postdate,reverse=True)
    cards=''
    for p in sorted_posts:
        cards+=f'''<a class="post-card" data-tag="{E(p['tag'])}" href="/blog/{p['slug']}.html"><span class="post-tag">{E(p['tag'])}</span><h2>{E(p['title'])}</h2><p>{E(p['blurb'])}</p><div class="post-meta">Scott Nguyen · {E(p['date'])}<br>Read article →</div></a>'''
    tags=['Marketplaces','E-commerce','Operations','Google Ads','ERP','SEO','Web','Growth']
    buttons='<button type="button" data-filter="all" aria-pressed="true">All</button>'+''.join(f'<button type="button" data-filter="{E(t)}" aria-pressed="false">{E("Systems & reporting" if t=="ERP" else t)}</button>' for t in tags)
    featured=[p for p in POSTS if p.get('featured')][:6]
    recommended=''.join(f'<a class="post-card" href="/blog/{p["slug"]}.html"><span class="post-tag">{E(p["tag"])}</span><h2>{E(p["title"])}</h2><p>{E(p["blurb"])}</p><span>Read guide →</span></a>' for p in featured)
    body=f'''<section class="page-hero"><div class="container"><p class="eyebrow">Insights from the operating work</p><h1>Practical guides for your e-commerce business.</h1><p class="lead">Explore marketplace accounts, inventory, fulfilment, advertising and systems. Each article connects to relevant support if you want help applying it.</p><a href="/services.html">Explore consulting services →</a></div></section>{'<section class="section soft"><div class="container"><h2>Start with these guides</h2><div class="post-list">'+recommended+'</div></div></section>' if featured else ''}<section class="section"><div class="container"><h2>Browse all insights</h2><label for="article-search">Search by topic or question</label><br><input class="search-field" id="article-search" type="search" placeholder="Try inventory, Amazon, Shopify or reporting" aria-controls="post-grid"><div class="filters" role="group" aria-label="Filter articles by topic">{buttons}</div><p class="small muted" id="filter-status" role="status" aria-live="polite">{len(POSTS)} articles</p><p id="no-articles" hidden>No matching articles. Try another term or choose All.</p><div class="post-list" id="post-grid">{cards}</div></div></section>{cta()}'''
    base('blog.html','E-commerce, Amazon & Walmart Guides | Simple Consulting','Practical guides on Amazon, Walmart, inventory, fulfilment, Google Ads, Shopify and e-commerce reporting, with relevant consulting support.',body)
    for p in sorted_posts:
        file='blog/'+p['slug']+'.html';canonical=url(file);s=service_for(p)
        # Stable URLs are stored in posts.json before any title edits.
        body_html=p['body']
        headings=[]
        def heading(m):
            text=plain(m.group(2)); hid='part-'+str(len(headings)+1);headings.append((hid,text))
            return '<h2 id="'+hid+'">'+m.group(2)+'</h2>'
        body_html=re.sub(r'<h([23])[^>]*>(.*?)</h[23]>',heading,body_html,flags=re.S)
        toc='<details class="article-toc"><summary>In this article</summary><ol>'+''.join(f'<li><a href="#{i}">{E(t)}</a></li>' for i,t in headings)+'</ol></details>' if headings else ''
        related=sorted([x for x in POSTS if x['slug']!=p['slug'] and service_for(x)['key']==s['key']],key=lambda x: (bool(x.get('featured')),postdate(x)),reverse=True)[:3]
        modified=' · Updated '+E(p['updated']) if p.get('updated') else ''
        body=f'''<div class="container"><div class="article-shell"><p class="crumbs"><a href="/">Home</a> / <a href="/blog.html">Insights</a> / {E(p['tag'])}</p><article><span class="post-tag">{E(p['tag'])}</span><h1>{E(p['title'])}</h1><p class="byline">By <a href="/about.html">Scott Nguyen</a> · Published {E(p['date'])}{modified}</p>{toc}<div class="article-body">{body_html}</div><aside class="related-service"><p class="eyebrow">Help with this part of the business</p><h2>{E(s['label'])}</h2><p>{E(s['fit'])}</p><a href="/{s['slug']}.html">Explore {E(s['label'].lower())} →</a><div class="actions"><a class="btn" href="/booking.html?service={s['key']}#start">Discuss this with Scott</a><a href="/booking.html?service={s['key']}#booking">Book a free call</a></div></aside></article><div class="article-related"><h2>Related reading</h2><ul>{''.join(f'<li><a href="/blog/{x["slug"]}.html">{E(x["title"])}</a></li>' for x in related)}</ul><a href="/blog.html">Browse all insights →</a></div></div></div>'''
        desc=p['blurb']
        schema=[{'@type':'BlogPosting','@id':canonical+'#article','headline':p['title'],'description':desc,'datePublished':postdate(p),'dateModified':p.get('updated',postdate(p)),'author':{'@id':SITE+'/about.html#scott'},'publisher':{'@id':SITE+'/#organization'},'mainEntityOfPage':{'@id':canonical+'#page'},'inLanguage':'en-CA','articleSection':p['tag']},{'@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'Home','item':SITE+'/'},{'@type':'ListItem','position':2,'name':'Insights','item':SITE+'/blog.html'},{'@type':'ListItem','position':3,'name':p['title'],'item':canonical}]}]
        base(file,p['title']+' | Simple Consulting',desc,body,schema)
        legacy=ROOT/(p['slug']+'.html')
        if legacy.exists():
            legacy.write_text(f'<!doctype html><html lang="en-CA"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{E(p["title"])}</title><link rel="canonical" href="{canonical}"><meta http-equiv="refresh" content="0;url={canonical}"></head><body><p>This article is available at <a href="{canonical}">{E(p["title"])}</a>.</p></body></html>')
    # Persist explicit slugs so future title edits do not change existing URLs.
    (ROOT/'posts.json').write_text(json.dumps(POSTS,ensure_ascii=False,indent=2)+'\n')
def sitemap():
    entries=[(url(f),TODAY) for f in CORE]
    entries +=[(url('blog/'+p['slug']+'.html'),p.get('updated',postdate(p))) for p in POSTS]
    xml='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+''.join(f'  <url><loc>{loc}</loc><lastmod>{date}</lastmod></url>\n' for loc,date in entries)+'</urlset>\n'
    (ROOT/'sitemap.xml').write_text(xml)
    (ROOT/'robots.txt').write_text('User-agent: *\nAllow: /\n\nSitemap: '+SITE+'/sitemap.xml\n')
def not_found():
    base('404.html','Page Not Found | Simple Consulting','Find the Simple Consulting service or guide you need.','<section class="section"><div class="container"><p class="eyebrow">404 · Page not found</p><h1>Let’s get you to the right place.</h1><p>The page may have moved. Browse the services or search the article library.</p><div class="actions"><a class="btn" href="/services.html">Explore services</a><a class="btn secondary" href="/blog.html">Find an article</a></div><a href="/">Return to the homepage</a></div></section>',robots='noindex,follow')
if __name__=='__main__':
    home();service_pages();services_hub();about();booking();privacy();blog();sitemap();not_found()
    print('Generated',len(CORE),'core pages and',len(POSTS),'articles; existing legacy URLs redirect to their canonical articles.')
